baseURL = "https://pboueri.github.io"
languageCode = "en-us"
title = "Patrick Boueri"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Personal website and portfolio"
  author = "Patrick Boueri"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 15

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[menu.main]]
  name = "Prompts"
  url = "/prompts/"
  weight = 40 